import { COLOR_PALLETES } from '../common/colorPalette';

const ALL_COLORS = {
  ...COLOR_PALLETES.PRIMARY,
  ...COLOR_PALLETES.GRAY,
  ...COLOR_PALLETES.YELLOW,
  ...COLOR_PALLETES.RED,
  ...COLOR_PALLETES.ORANGE,
  ...COLOR_PALLETES.PURPLE,
};

const BACKGROUND_COLOR = ALL_COLORS.BLACK;

export default { ...ALL_COLORS, BACKGROUND_COLOR };
